const PermissionKeys = {
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_REFRESH: 'AUTH_REFRESH',
  AUTH_LOGOUT: 'AUTH_LOGOUT',

  USER_CREATE: 'USER_CREATE',
  USER_READ: 'USER_READ',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_READ_SELF: 'USER_READ_SELF',
  USER_UPDATE_SELF: 'USER_UPDATE_SELF',
  USER_DELETE_SELF: 'USER_DELETE_SELF',

  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_DELETE: 'ROLE_DELETE',
  ROLE_READ: 'ROLE_READ',
  ROLE_ASSIGN_PERMISSION: 'ROLE_ASSIGN_PERMISSION',
} as const;

export const AllPermissions = Object.values(PermissionKeys);
